### ISSUE TITLE
AttributeError: module 'pysam.libcfaidx' has no attribute 'FastxRecord'

### ISSUE THREAD

**Issue by douym** [alimanfoo/pysamstats#101]
Hi,

I'm using python3.6.8.

I installed  pysam.__version__ '0.11.2.2' and 

pysamstats1.0.1:

/usr/local/lib/python3.6/site-packages# pip install pysamstats==1.0.1
Requirement already satisfied: pysamstats==1.0.1 in /usr/local/lib/python3.6/site-packages (1.0.1)

However, when I try to import pysamstats, there were errors:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "/usr/local/lib/python3.6/site-packages/pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
  File "libcfaidx.pxd", line 52, in init pysamstats.opt
AttributeError: module 'pysam.libcfaidx' has no attribute 'FastxRecord'

Could you tell how to fix that? thanks a lot!

**Comment by douym** [comment]
I fixed that by updating pysam to 0.15.2 and updating pysamstats to 1.1.2.

**Comment by alimanfoo** [comment]
Cool, thanks for letting us know.
