### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by yasinkaymaz** [alimanfoo/pysamstats#71]
Hi,

I have been trying to install and use pysamstats. However, I am getting errors below.
First I updated my pysam. 
Then, installed pysamstats with pip. (I also tried manual install but did not work). I didn't get ant error during the install, but when I try to execute it I get this error below.

```
$ pysamstats --help
Traceback (most recent call last):
  File "/usr/local/bin/pysamstats", line 4, in <module>
    __import__('pkg_resources').run_script('pysamstats==1.0.1', 'pysamstats')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/pysamstats-1.0.1-py2.7-macosx-10.12-intel.egg/EGG-INFO/scripts/pysamstats", line 10, in <module>

  File "build/bdist.macosx-10.12-intel/egg/pysamstats/__init__.py", line 8, in <module>
  File "build/bdist.macosx-10.12-intel/egg/pysamstats/pileup.py", line 6, in <module>
  File "build/bdist.macosx-10.12-intel/egg/pysamstats/opt.py", line 7, in <module>
  File "build/bdist.macosx-10.12-intel/egg/pysamstats/opt.py", line 6, in __bootstrap__
  File "libcfaidx.pxd", line 51, in init pysamstats.opt (pysamstats/opt.c:34893)
AttributeError: 'module' object has no attribute 'PersistentFastqProxy'
```

```
$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> print pysam.__version__
0.12.0.1
>>> import pysamstats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
ImportError: No module named opt
```
Here is the output from manual install:
```
sudo python setup.py install
[pysamstats] build with Cython
running install
running bdist_egg
running egg_info
writing pysamstats.egg-info/PKG-INFO
writing top-level names to pysamstats.egg-info/top_level.txt
writing dependency_links to pysamstats.egg-info/dependency_links.txt
reading manifest file 'pysamstats.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pyx'
warning: no files found matching '*.pxd'
warning: no files found matching '*.c'
writing manifest file 'pysamstats.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.12-intel/egg
running install_lib
running build_py
running build_ext
creating build/bdist.macosx-10.12-intel/egg
creating build/bdist.macosx-10.12-intel/egg/pysamstats
copying build/lib.macosx-10.12-intel-2.7/pysamstats/__init__.py -> build/bdist.macosx-10.12-intel/egg/pysamstats
copying build/lib.macosx-10.12-intel-2.7/pysamstats/binned.py -> build/bdist.macosx-10.12-intel/egg/pysamstats
copying build/lib.macosx-10.12-intel-2.7/pysamstats/config.py -> build/bdist.macosx-10.12-intel/egg/pysamstats
copying build/lib.macosx-10.12-intel-2.7/pysamstats/io.py -> build/bdist.macosx-10.12-intel/egg/pysamstats
copying build/lib.macosx-10.12-intel-2.7/pysamstats/opt.so -> build/bdist.macosx-10.12-intel/egg/pysamstats
copying build/lib.macosx-10.12-intel-2.7/pysamstats/pileup.py -> build/bdist.macosx-10.12-intel/egg/pysamstats
creating build/bdist.macosx-10.12-intel/egg/pysamstats/test
copying build/lib.macosx-10.12-intel-2.7/pysamstats/test/__init__.py -> build/bdist.macosx-10.12-intel/egg/pysamstats/test
copying build/lib.macosx-10.12-intel-2.7/pysamstats/test/test_binned.py -> build/bdist.macosx-10.12-intel/egg/pysamstats/test
copying build/lib.macosx-10.12-intel-2.7/pysamstats/test/test_pileup.py -> build/bdist.macosx-10.12-intel/egg/pysamstats/test
copying build/lib.macosx-10.12-intel-2.7/pysamstats/test/util.py -> build/bdist.macosx-10.12-intel/egg/pysamstats/test
copying build/lib.macosx-10.12-intel-2.7/pysamstats/util.py -> build/bdist.macosx-10.12-intel/egg/pysamstats
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/binned.py to binned.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/config.py to config.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/io.py to io.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/pileup.py to pileup.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/test/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/test/test_binned.py to test_binned.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/test/test_pileup.py to test_pileup.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/test/util.py to util.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/util.py to util.pyc
creating stub loader for pysamstats/opt.so
byte-compiling build/bdist.macosx-10.12-intel/egg/pysamstats/opt.py to opt.pyc
creating build/bdist.macosx-10.12-intel/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.12-intel/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.macosx-10.12-intel/egg/EGG-INFO/scripts
copying build/scripts-2.7/pysamstats -> build/bdist.macosx-10.12-intel/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.12-intel/egg/EGG-INFO/scripts/pysamstats to 755
copying pysamstats.egg-info/PKG-INFO -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying pysamstats.egg-info/SOURCES.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying pysamstats.egg-info/dependency_links.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying pysamstats.egg-info/top_level.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
writing build/bdist.macosx-10.12-intel/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/pysamstats-1.0.1-py2.7-macosx-10.12-intel.egg' and adding 'build/bdist.macosx-10.12-intel/egg' to it
removing 'build/bdist.macosx-10.12-intel/egg' (and everything under it)
Processing pysamstats-1.0.1-py2.7-macosx-10.12-intel.egg
Copying pysamstats-1.0.1-py2.7-macosx-10.12-intel.egg to /Library/Python/2.7/site-packages
Adding pysamstats 1.0.1 to easy-install.pth file
Installing pysamstats script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/pysamstats-1.0.1-py2.7-macosx-10.12-intel.egg
Processing dependencies for pysamstats==1.0.1
Finished processing dependencies for pysamstats==1.0.1
```
Here is my cython version if it helps:
```
 >>> print Cython.__version__
0.26.1
```

Thanks,

**Comment by alimanfoo** [comment]
Apologies, at the moment you need to install pysam 0.11, e.g.:

```
pip install pysam==0.11.2.2
pip install pysamstats
```
